-- Run this SQL in your Supabase SQL Editor to create the tables
-- Go to: https://supabase.com/dashboard/project/mstyccuqvedtrceuyqqa/sql

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Customers table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  name TEXT,
  phone TEXT NOT NULL,
  notes TEXT,
  branch_id INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  order_number TEXT NOT NULL UNIQUE,
  branch_id INTEGER NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(id),
  piece_type TEXT NOT NULL,
  details TEXT,
  price REAL NOT NULL,
  paid REAL DEFAULT 0,
  payment_method TEXT NOT NULL CHECK(payment_method IN ('cash', 'card')),
  status TEXT NOT NULL CHECK(status IN ('intake', 'cutting', 'sewing', 'ready', 'delivered')),
  receive_date DATE,
  delivery_date DATE,
  created_by BIGINT,
  fabric_source TEXT CHECK(fabric_source IN ('customer', 'shop')) DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  piece_type TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price REAL NOT NULL,
  total_price REAL NOT NULL DEFAULT 0,
  fabric_source TEXT CHECK(fabric_source IN ('customer', 'shop')) DEFAULT 'customer',
  fabric_price REAL NOT NULL DEFAULT 0,
  details TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Order Payments table
CREATE TABLE IF NOT EXISTS order_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  amount REAL NOT NULL,
  method TEXT NOT NULL CHECK(method IN ('cash', 'card')),
  note TEXT,
  created_by BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Order Measurements table
CREATE TABLE IF NOT EXISTS order_measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  chest REAL,
  waist REAL,
  hips REAL,
  length REAL,
  sleeve REAL,
  shoulder REAL,
  notes TEXT,
  taken_by BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Order Tasks table
CREATE TABLE IF NOT EXISTS order_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  order_item_id BIGINT REFERENCES order_items(id) ON DELETE CASCADE,
  task_type TEXT NOT NULL CHECK(task_type IN ('cutting', 'sewing', 'design')),
  assigned_to BIGINT,
  wage_type TEXT NOT NULL CHECK(wage_type IN ('percentage', 'fixed')),
  wage_rate REAL NOT NULL,
  wage_amount REAL NOT NULL,
  task_quantity INTEGER DEFAULT 1,
  status TEXT NOT NULL CHECK(status IN ('pending', 'in_progress', 'done')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  notes TEXT,
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Expenses table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  category TEXT NOT NULL CHECK(category IN ('rent', 'utilities', 'materials', 'fabric', 'supplies', 'salaries', 'other')),
  description TEXT NOT NULL,
  amount REAL NOT NULL,
  expense_date DATE NOT NULL,
  branch_id INTEGER NOT NULL,
  created_by BIGINT,
  note TEXT,
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Users table (for workers and admin staff)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL CHECK(role IN ('admin', 'manager', 'reception', 'worker')),
  worker_type TEXT CHECK(worker_type IN ('tailor', 'master_cutter')),
  branch_id INTEGER NOT NULL,
  base_salary REAL DEFAULT 0,
  default_rate REAL DEFAULT 0,
  active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source)
);

-- Piece Types table (garment types with prices)
CREATE TABLE IF NOT EXISTS piece_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT NOT NULL,
  name_en TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  category TEXT NOT NULL CHECK(category IN ('custom_wear', 'abaya', 'uniform', 'alteration', 'special')),
  active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  base_price REAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_source TEXT NOT NULL,
  UNIQUE(local_id, sync_source),
  UNIQUE(name_en, sync_source)
);

-- Indexes for better performance
CREATE INDEX IF NOT EXISTS idx_customers_local ON customers(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_orders_local ON orders(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_items_local ON order_items(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_payments_local ON order_payments(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_order_payments_order ON order_payments(order_id);
CREATE INDEX IF NOT EXISTS idx_order_measurements_local ON order_measurements(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_order_measurements_order ON order_measurements(order_id);
CREATE INDEX IF NOT EXISTS idx_order_tasks_local ON order_tasks(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_order_tasks_order ON order_tasks(order_id);
CREATE INDEX IF NOT EXISTS idx_expenses_local ON expenses(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_users_local ON users(local_id, sync_source);
CREATE INDEX IF NOT EXISTS idx_piece_types_local ON piece_types(local_id, sync_source);

-- Enable Row Level Security (optional - can be disabled for simplicity)
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE piece_types ENABLE ROW LEVEL SECURITY;

-- Allow public access for sync (simple approach - you can restrict later)
-- Drop policies first if they exist
DROP POLICY IF EXISTS "Allow all access" ON customers;
DROP POLICY IF EXISTS "Allow all access" ON orders;
DROP POLICY IF EXISTS "Allow all access" ON order_items;
DROP POLICY IF EXISTS "Allow all access" ON order_payments;
DROP POLICY IF EXISTS "Allow all access" ON order_measurements;
DROP POLICY IF EXISTS "Allow all access" ON order_tasks;
DROP POLICY IF EXISTS "Allow all access" ON expenses;
DROP POLICY IF EXISTS "Allow all access" ON users;
DROP POLICY IF EXISTS "Allow all access" ON piece_types;

-- Create policies
CREATE POLICY "Allow all access" ON customers FOR ALL USING (true);
CREATE POLICY "Allow all access" ON orders FOR ALL USING (true);
CREATE POLICY "Allow all access" ON order_items FOR ALL USING (true);
CREATE POLICY "Allow all access" ON order_payments FOR ALL USING (true);
CREATE POLICY "Allow all access" ON order_measurements FOR ALL USING (true);
CREATE POLICY "Allow all access" ON order_tasks FOR ALL USING (true);
CREATE POLICY "Allow all access" ON expenses FOR ALL USING (true);
CREATE POLICY "Allow all access" ON users FOR ALL USING (true);
CREATE POLICY "Allow all access" ON piece_types FOR ALL USING (true);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers to auto-update updated_at
DROP TRIGGER IF EXISTS update_customers_updated_at ON customers;
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_order_items_updated_at ON order_items;
CREATE TRIGGER update_order_items_updated_at BEFORE UPDATE ON order_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_expenses_updated_at ON expenses;
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON expenses
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_piece_types_updated_at ON piece_types;
CREATE TRIGGER update_piece_types_updated_at BEFORE UPDATE ON piece_types
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
